import { StyleSheet } from 'react-native';

export const appStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#03b524a2',
  },
  content: {
    flex: 1,
    paddingHorizontal: 20,
  },
  section: {
    marginTop: 20,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  addButton: {
    backgroundColor: '#278a2a98',
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#0273069c',
  },
  addButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000000',
  },
  taskContainer: {
    backgroundColor: '#cdffd7',
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: '#058a19',
  },
  doneAtContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 15,
    marginTop: 5,
    borderTopWidth: 0,
  },
  doneAtLabel: {
    fontSize: 16,
    fontWeight: '600',
  },
  doneAtTime: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4CAF50',
  },
  progressContainer: {
    backgroundColor: '#cdffd7',
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: '#058a19',
  },
  progressItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderWidth: 2,
    borderColor: '#333',
    borderRadius: 4,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#333',
  },
  checkmark: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  progressTaskText: {
    fontSize: 16,
    marginLeft: 12,
  },
  emptyText: {
    fontSize: 16,
    color: '#999',
    textAlign: 'center',
    paddingVertical: 20,
  },
  totalTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  totalTimeLabel: {
    fontSize: 16,
    fontWeight: '600',
  },
  totalTimeValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#4CAF50',
  },
  bottomSheetToggle: {
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    backgroundColor: '#3baf50',
    paddingVertical: 10,
    alignItems: 'center',
    zIndex: 10,
    borderTopWidth: 1,
    borderTopColor: '#05890e',
  },
  dragHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#068111',
    borderRadius: 2,
    marginBottom: 5,
  },
  bottomSheetArrow: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  bottomSheet: {
    position: 'absolute',
    bottom: 65,
    left: 0,
    right: 0,
    backgroundColor: '#5abc6c',
    borderTopWidth: 1,
    borderTopColor: '#088d04',
    maxHeight: '60%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  bottomSheetHandle: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  bottomSection: {
    marginBottom: 20,
    paddingHorizontal: 20,
  },
});
